# Generated by Django 2.2 on 2021-04-27 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=250)),
                ('target', models.IntegerField()),
                ('frequency', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='tags.Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
