# Generated by Django 2.2 on 2021-04-28 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='member',
            field=models.ManyToManyField(related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_newsletter', to=settings.AUTH_USER_MODEL),
        ),
    ]
