# Generated by Django 2.2 on 2021-04-28 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0002_auto_20210427_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletters',
            name='member',
        ),
        migrations.AddField(
            model_name='newsletters',
            name='members',
            field=models.ManyToManyField(related_name='members_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
