# Generated by Django 2.2 on 2021-05-01 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_auto_20210501_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
